### ISSUE TITLE
Build fails when trying to download opencv

### ISSUE THREAD

**Issue by MarcBritton** [headupinclouds/hunter_eos_example#2]
I built on OSX according to the instructions from the github README.md.

The build process gets to the step of trying to download opencv to build it but the hash of the downloaded version never matches the expected value. Below is a log from the 5th download attempt:

```
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='/Users/user/.hunter/_Base/Download/OpenCV/3.2.0-p2/9921920/v3.2.0-p2.tar.gz'
-- SHA1 hash of
    /Users/user/.hunter/_Base/Download/OpenCV/3.2.0-p2/9921920/v3.2.0-p2.tar.gz
  does not match expected value
    expected: '99219206c4fb9b5b6f60e03112746461baf6c9ab'
      actual: 'ea8f612eea55dfa6d2f3669d5e9eb4240417444b'
-- Hash mismatch, removing...
CMake Error at Build/OpenCV-Release-prefix/src/OpenCV-Release-stamp/download-OpenCV-Release.cmake:157 (message):
  Each download failed!
```

The build fails after this point.

**Comment by headupinclouds** [comment]
I just noticed this, sorry for the delay.  This issue is due to a recent github changes where they recreated a bunch of tagged releases, which invalidated the stored SHA1.  I believe most of them have been fixed in the latest release.  I will update the sample project to the latest hunter release.

Related discussion:
https://github.com/ruslo/hunter/issues/1032#issuecomment-329382772

**Comment by headupinclouds** [comment]
Merged: https://github.com/headupinclouds/hunter_eos_example/pull/3
